databases:
  # ✅ Free PostgreSQL Database
  - name: farm-management-db
    plan: free
    region: oregon

services:
  # ✅ Django Web Application
  - type: web
    name: farm-management-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: "/bin/sh -c 'echo \"🚀 Starting Django application...\" && mkdir -p /app/logs && echo \"⏳ Waiting for database connection...\" && until nc -z -v -w30 \"${DB_HOST:-db}\" 5432; do echo \"Waiting for database at ${DB_HOST:-db}:5432...\"; sleep 2; done && echo \"✅ Database is up and running!\" && echo \"📊 Applying database migrations...\" && python manage.py migrate --noinput && echo \"📁 Collecting static files...\" && python manage.py collectstatic --noinput && echo \"🌐 Starting Gunicorn server...\" && exec gunicorn farm_management.wsgi:application --bind 0.0.0.0:${PORT:-8000} --workers 3 --timeout 120 --access-logfile - --error-logfile -'"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: farm_management.settings_production
      - key: DB_NAME
        fromDatabase:
          name: farm-management-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: farm-management-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: farm-management-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: farm-management-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: farm-management-db
          property: port
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://*.onrender.com,http://localhost:3000"
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: FRONTEND_URL
        value: "https://your-frontend-app.onrender.com"
    healthCheckPath: /api/health/
